typography_spectrum: 0.91211
color:
  brandColors:
    - '#ffffff'
    - '#1a1c19'
    - '#496e2b'
    - '#9f6f6b'
    - '#9dbe71'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/d4ecbf3a-5cfd-4e03-90ad-cfd87885c16e.png
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Chenopodium.org
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6fd99fd5-5b1d-4ed2-a26c-e36ca999982f.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Chenopodium.org
purpose: []
