name: Pitseed
favicon: null
layout_spectrum: 0.51022
typography_spectrum: 0.91211
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#70a753'
    - '#0d0f0c'
    - '#3c5f1f'
    - '#af9285'
    - '#b4149b'
  brandStrength: 0.75
  lightness: 0.7548491
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
