name: Pitseed
favicon: null
layout_spectrum: 0.51022
typography_spectrum: 0.91211
title: Chenopodium.org
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a1c19'
    - '#496e2b'
    - '#9f6f6b'
    - '#9dbe71'
  brandStrength: 0.75
  lightness: 0.7548491
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
